// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noise.proto

package grpc.noise;

public interface checkNoiseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkNoise)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float firstSound = 1;</code>
   */
  float getFirstSound();
}
