// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noise.proto

package grpc.noise;

public final class NoiseRoomImpl {
  private NoiseRoomImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_checkNoise_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_checkNoise_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_noiseAlarm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_noiseAlarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013noise.proto\" \n\ncheckNoise\022\022\n\nfirstSoun" +
      "d\030\001 \001(\002\" \n\nnoiseAlarm\022\022\n\nsoundAlarm\030\001 \001(" +
      "\t2,\n\005noise\022#\n\005Sound\022\013.checkNoise\032\013.noise" +
      "Alarm\"\000B\035\n\ngrpc.noiseB\rNoiseRoomImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_checkNoise_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_checkNoise_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_checkNoise_descriptor,
        new java.lang.String[] { "FirstSound", });
    internal_static_noiseAlarm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_noiseAlarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_noiseAlarm_descriptor,
        new java.lang.String[] { "SoundAlarm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
