// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: noise.proto

package grpc.noise;

public interface noiseAlarmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:noiseAlarm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string soundAlarm = 1;</code>
   */
  java.lang.String getSoundAlarm();
  /**
   * <code>string soundAlarm = 1;</code>
   */
  com.google.protobuf.ByteString
      getSoundAlarmBytes();
}
