// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.temperature;

public interface checkTemperatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkTemperature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float firstTemperature = 1;</code>
   */
  float getFirstTemperature();
}
