// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.temperature;

public final class TempRoomImpl {
  private TempRoomImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_checkTemperature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_checkTemperature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperatureAlarm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperatureAlarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021temperature.proto\",\n\020checkTemperature\022" +
      "\030\n\020firstTemperature\030\001 \001(\002\"%\n\020temperature" +
      "Alarm\022\021\n\ttempAlarm\030\001 \001(\t2H\n\013temperature\022" +
      "9\n\017sendTemperature\022\021.checkTemperature\032\021." +
      "temperatureAlarm\"\000B\"\n\020grpc.temperatureB\014" +
      "TempRoomImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_checkTemperature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_checkTemperature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_checkTemperature_descriptor,
        new java.lang.String[] { "FirstTemperature", });
    internal_static_temperatureAlarm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_temperatureAlarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperatureAlarm_descriptor,
        new java.lang.String[] { "TempAlarm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
