// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.temperature;

public interface temperatureAlarmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperatureAlarm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tempAlarm = 1;</code>
   */
  java.lang.String getTempAlarm();
  /**
   * <code>string tempAlarm = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempAlarmBytes();
}
