// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invasionEvent.proto

package grpc.invasionEvent;

/**
 * Protobuf type {@code checkRoomStatus}
 */
public  final class checkRoomStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:checkRoomStatus)
    checkRoomStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use checkRoomStatus.newBuilder() to construct.
  private checkRoomStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private checkRoomStatus() {
    firstRoomSound_ = 0F;
    firstRoomTemperature_ = 0F;
    firstRoomPressure_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private checkRoomStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            firstRoomSound_ = input.readFloat();
            break;
          }
          case 21: {

            firstRoomTemperature_ = input.readFloat();
            break;
          }
          case 29: {

            firstRoomPressure_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.invasionEvent.InvasionEventImpl.internal_static_checkRoomStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.invasionEvent.InvasionEventImpl.internal_static_checkRoomStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.invasionEvent.checkRoomStatus.class, grpc.invasionEvent.checkRoomStatus.Builder.class);
  }

  public static final int FIRSTROOMSOUND_FIELD_NUMBER = 1;
  private float firstRoomSound_;
  /**
   * <code>float firstRoomSound = 1;</code>
   */
  public float getFirstRoomSound() {
    return firstRoomSound_;
  }

  public static final int FIRSTROOMTEMPERATURE_FIELD_NUMBER = 2;
  private float firstRoomTemperature_;
  /**
   * <code>float firstRoomTemperature = 2;</code>
   */
  public float getFirstRoomTemperature() {
    return firstRoomTemperature_;
  }

  public static final int FIRSTROOMPRESSURE_FIELD_NUMBER = 3;
  private float firstRoomPressure_;
  /**
   * <code>float firstRoomPressure = 3;</code>
   */
  public float getFirstRoomPressure() {
    return firstRoomPressure_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (firstRoomSound_ != 0F) {
      output.writeFloat(1, firstRoomSound_);
    }
    if (firstRoomTemperature_ != 0F) {
      output.writeFloat(2, firstRoomTemperature_);
    }
    if (firstRoomPressure_ != 0F) {
      output.writeFloat(3, firstRoomPressure_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (firstRoomSound_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, firstRoomSound_);
    }
    if (firstRoomTemperature_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, firstRoomTemperature_);
    }
    if (firstRoomPressure_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, firstRoomPressure_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.invasionEvent.checkRoomStatus)) {
      return super.equals(obj);
    }
    grpc.invasionEvent.checkRoomStatus other = (grpc.invasionEvent.checkRoomStatus) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getFirstRoomSound())
        == java.lang.Float.floatToIntBits(
            other.getFirstRoomSound()));
    result = result && (
        java.lang.Float.floatToIntBits(getFirstRoomTemperature())
        == java.lang.Float.floatToIntBits(
            other.getFirstRoomTemperature()));
    result = result && (
        java.lang.Float.floatToIntBits(getFirstRoomPressure())
        == java.lang.Float.floatToIntBits(
            other.getFirstRoomPressure()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRSTROOMSOUND_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFirstRoomSound());
    hash = (37 * hash) + FIRSTROOMTEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFirstRoomTemperature());
    hash = (37 * hash) + FIRSTROOMPRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFirstRoomPressure());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.invasionEvent.checkRoomStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.invasionEvent.checkRoomStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.invasionEvent.checkRoomStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.invasionEvent.checkRoomStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code checkRoomStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:checkRoomStatus)
      grpc.invasionEvent.checkRoomStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.invasionEvent.InvasionEventImpl.internal_static_checkRoomStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.invasionEvent.InvasionEventImpl.internal_static_checkRoomStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.invasionEvent.checkRoomStatus.class, grpc.invasionEvent.checkRoomStatus.Builder.class);
    }

    // Construct using grpc.invasionEvent.checkRoomStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      firstRoomSound_ = 0F;

      firstRoomTemperature_ = 0F;

      firstRoomPressure_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.invasionEvent.InvasionEventImpl.internal_static_checkRoomStatus_descriptor;
    }

    @java.lang.Override
    public grpc.invasionEvent.checkRoomStatus getDefaultInstanceForType() {
      return grpc.invasionEvent.checkRoomStatus.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.invasionEvent.checkRoomStatus build() {
      grpc.invasionEvent.checkRoomStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.invasionEvent.checkRoomStatus buildPartial() {
      grpc.invasionEvent.checkRoomStatus result = new grpc.invasionEvent.checkRoomStatus(this);
      result.firstRoomSound_ = firstRoomSound_;
      result.firstRoomTemperature_ = firstRoomTemperature_;
      result.firstRoomPressure_ = firstRoomPressure_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.invasionEvent.checkRoomStatus) {
        return mergeFrom((grpc.invasionEvent.checkRoomStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.invasionEvent.checkRoomStatus other) {
      if (other == grpc.invasionEvent.checkRoomStatus.getDefaultInstance()) return this;
      if (other.getFirstRoomSound() != 0F) {
        setFirstRoomSound(other.getFirstRoomSound());
      }
      if (other.getFirstRoomTemperature() != 0F) {
        setFirstRoomTemperature(other.getFirstRoomTemperature());
      }
      if (other.getFirstRoomPressure() != 0F) {
        setFirstRoomPressure(other.getFirstRoomPressure());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.invasionEvent.checkRoomStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.invasionEvent.checkRoomStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float firstRoomSound_ ;
    /**
     * <code>float firstRoomSound = 1;</code>
     */
    public float getFirstRoomSound() {
      return firstRoomSound_;
    }
    /**
     * <code>float firstRoomSound = 1;</code>
     */
    public Builder setFirstRoomSound(float value) {
      
      firstRoomSound_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float firstRoomSound = 1;</code>
     */
    public Builder clearFirstRoomSound() {
      
      firstRoomSound_ = 0F;
      onChanged();
      return this;
    }

    private float firstRoomTemperature_ ;
    /**
     * <code>float firstRoomTemperature = 2;</code>
     */
    public float getFirstRoomTemperature() {
      return firstRoomTemperature_;
    }
    /**
     * <code>float firstRoomTemperature = 2;</code>
     */
    public Builder setFirstRoomTemperature(float value) {
      
      firstRoomTemperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float firstRoomTemperature = 2;</code>
     */
    public Builder clearFirstRoomTemperature() {
      
      firstRoomTemperature_ = 0F;
      onChanged();
      return this;
    }

    private float firstRoomPressure_ ;
    /**
     * <code>float firstRoomPressure = 3;</code>
     */
    public float getFirstRoomPressure() {
      return firstRoomPressure_;
    }
    /**
     * <code>float firstRoomPressure = 3;</code>
     */
    public Builder setFirstRoomPressure(float value) {
      
      firstRoomPressure_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float firstRoomPressure = 3;</code>
     */
    public Builder clearFirstRoomPressure() {
      
      firstRoomPressure_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:checkRoomStatus)
  }

  // @@protoc_insertion_point(class_scope:checkRoomStatus)
  private static final grpc.invasionEvent.checkRoomStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.invasionEvent.checkRoomStatus();
  }

  public static grpc.invasionEvent.checkRoomStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<checkRoomStatus>
      PARSER = new com.google.protobuf.AbstractParser<checkRoomStatus>() {
    @java.lang.Override
    public checkRoomStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new checkRoomStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<checkRoomStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<checkRoomStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.invasionEvent.checkRoomStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

