// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invasionEvent.proto

package grpc.invasionEvent;

public interface checkRoomStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkRoomStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float firstRoomSound = 1;</code>
   */
  float getFirstRoomSound();

  /**
   * <code>float firstRoomTemperature = 2;</code>
   */
  float getFirstRoomTemperature();

  /**
   * <code>float firstRoomPressure = 3;</code>
   */
  float getFirstRoomPressure();
}
