// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invasionEvent.proto

package grpc.invasionEvent;

public interface invasionAlarmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:invasionAlarm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string soundIntensityAlarm = 1;</code>
   */
  java.lang.String getSoundIntensityAlarm();
  /**
   * <code>string soundIntensityAlarm = 1;</code>
   */
  com.google.protobuf.ByteString
      getSoundIntensityAlarmBytes();

  /**
   * <code>string objectTempAlarm = 2;</code>
   */
  java.lang.String getObjectTempAlarm();
  /**
   * <code>string objectTempAlarm = 2;</code>
   */
  com.google.protobuf.ByteString
      getObjectTempAlarmBytes();

  /**
   * <code>string airPressureAlarm = 3;</code>
   */
  java.lang.String getAirPressureAlarm();
  /**
   * <code>string airPressureAlarm = 3;</code>
   */
  com.google.protobuf.ByteString
      getAirPressureAlarmBytes();
}
