// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invasionEvent.proto

package grpc.invasionEvent;

/**
 * Protobuf type {@code invasionAlarm}
 */
public  final class invasionAlarm extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:invasionAlarm)
    invasionAlarmOrBuilder {
private static final long serialVersionUID = 0L;
  // Use invasionAlarm.newBuilder() to construct.
  private invasionAlarm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private invasionAlarm() {
    soundIntensityAlarm_ = "";
    objectTempAlarm_ = "";
    airPressureAlarm_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private invasionAlarm(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            soundIntensityAlarm_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            objectTempAlarm_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            airPressureAlarm_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.invasionEvent.InvasionEventImpl.internal_static_invasionAlarm_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.invasionEvent.InvasionEventImpl.internal_static_invasionAlarm_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.invasionEvent.invasionAlarm.class, grpc.invasionEvent.invasionAlarm.Builder.class);
  }

  public static final int SOUNDINTENSITYALARM_FIELD_NUMBER = 1;
  private volatile java.lang.Object soundIntensityAlarm_;
  /**
   * <code>string soundIntensityAlarm = 1;</code>
   */
  public java.lang.String getSoundIntensityAlarm() {
    java.lang.Object ref = soundIntensityAlarm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      soundIntensityAlarm_ = s;
      return s;
    }
  }
  /**
   * <code>string soundIntensityAlarm = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSoundIntensityAlarmBytes() {
    java.lang.Object ref = soundIntensityAlarm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      soundIntensityAlarm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECTTEMPALARM_FIELD_NUMBER = 2;
  private volatile java.lang.Object objectTempAlarm_;
  /**
   * <code>string objectTempAlarm = 2;</code>
   */
  public java.lang.String getObjectTempAlarm() {
    java.lang.Object ref = objectTempAlarm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectTempAlarm_ = s;
      return s;
    }
  }
  /**
   * <code>string objectTempAlarm = 2;</code>
   */
  public com.google.protobuf.ByteString
      getObjectTempAlarmBytes() {
    java.lang.Object ref = objectTempAlarm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectTempAlarm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AIRPRESSUREALARM_FIELD_NUMBER = 3;
  private volatile java.lang.Object airPressureAlarm_;
  /**
   * <code>string airPressureAlarm = 3;</code>
   */
  public java.lang.String getAirPressureAlarm() {
    java.lang.Object ref = airPressureAlarm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      airPressureAlarm_ = s;
      return s;
    }
  }
  /**
   * <code>string airPressureAlarm = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAirPressureAlarmBytes() {
    java.lang.Object ref = airPressureAlarm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      airPressureAlarm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSoundIntensityAlarmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, soundIntensityAlarm_);
    }
    if (!getObjectTempAlarmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, objectTempAlarm_);
    }
    if (!getAirPressureAlarmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, airPressureAlarm_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSoundIntensityAlarmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, soundIntensityAlarm_);
    }
    if (!getObjectTempAlarmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, objectTempAlarm_);
    }
    if (!getAirPressureAlarmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, airPressureAlarm_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.invasionEvent.invasionAlarm)) {
      return super.equals(obj);
    }
    grpc.invasionEvent.invasionAlarm other = (grpc.invasionEvent.invasionAlarm) obj;

    boolean result = true;
    result = result && getSoundIntensityAlarm()
        .equals(other.getSoundIntensityAlarm());
    result = result && getObjectTempAlarm()
        .equals(other.getObjectTempAlarm());
    result = result && getAirPressureAlarm()
        .equals(other.getAirPressureAlarm());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOUNDINTENSITYALARM_FIELD_NUMBER;
    hash = (53 * hash) + getSoundIntensityAlarm().hashCode();
    hash = (37 * hash) + OBJECTTEMPALARM_FIELD_NUMBER;
    hash = (53 * hash) + getObjectTempAlarm().hashCode();
    hash = (37 * hash) + AIRPRESSUREALARM_FIELD_NUMBER;
    hash = (53 * hash) + getAirPressureAlarm().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.invasionEvent.invasionAlarm parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.invasionEvent.invasionAlarm parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.invasionEvent.invasionAlarm parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.invasionEvent.invasionAlarm parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.invasionEvent.invasionAlarm prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code invasionAlarm}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:invasionAlarm)
      grpc.invasionEvent.invasionAlarmOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.invasionEvent.InvasionEventImpl.internal_static_invasionAlarm_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.invasionEvent.InvasionEventImpl.internal_static_invasionAlarm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.invasionEvent.invasionAlarm.class, grpc.invasionEvent.invasionAlarm.Builder.class);
    }

    // Construct using grpc.invasionEvent.invasionAlarm.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      soundIntensityAlarm_ = "";

      objectTempAlarm_ = "";

      airPressureAlarm_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.invasionEvent.InvasionEventImpl.internal_static_invasionAlarm_descriptor;
    }

    @java.lang.Override
    public grpc.invasionEvent.invasionAlarm getDefaultInstanceForType() {
      return grpc.invasionEvent.invasionAlarm.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.invasionEvent.invasionAlarm build() {
      grpc.invasionEvent.invasionAlarm result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.invasionEvent.invasionAlarm buildPartial() {
      grpc.invasionEvent.invasionAlarm result = new grpc.invasionEvent.invasionAlarm(this);
      result.soundIntensityAlarm_ = soundIntensityAlarm_;
      result.objectTempAlarm_ = objectTempAlarm_;
      result.airPressureAlarm_ = airPressureAlarm_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.invasionEvent.invasionAlarm) {
        return mergeFrom((grpc.invasionEvent.invasionAlarm)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.invasionEvent.invasionAlarm other) {
      if (other == grpc.invasionEvent.invasionAlarm.getDefaultInstance()) return this;
      if (!other.getSoundIntensityAlarm().isEmpty()) {
        soundIntensityAlarm_ = other.soundIntensityAlarm_;
        onChanged();
      }
      if (!other.getObjectTempAlarm().isEmpty()) {
        objectTempAlarm_ = other.objectTempAlarm_;
        onChanged();
      }
      if (!other.getAirPressureAlarm().isEmpty()) {
        airPressureAlarm_ = other.airPressureAlarm_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.invasionEvent.invasionAlarm parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.invasionEvent.invasionAlarm) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object soundIntensityAlarm_ = "";
    /**
     * <code>string soundIntensityAlarm = 1;</code>
     */
    public java.lang.String getSoundIntensityAlarm() {
      java.lang.Object ref = soundIntensityAlarm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        soundIntensityAlarm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string soundIntensityAlarm = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSoundIntensityAlarmBytes() {
      java.lang.Object ref = soundIntensityAlarm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        soundIntensityAlarm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string soundIntensityAlarm = 1;</code>
     */
    public Builder setSoundIntensityAlarm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      soundIntensityAlarm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string soundIntensityAlarm = 1;</code>
     */
    public Builder clearSoundIntensityAlarm() {
      
      soundIntensityAlarm_ = getDefaultInstance().getSoundIntensityAlarm();
      onChanged();
      return this;
    }
    /**
     * <code>string soundIntensityAlarm = 1;</code>
     */
    public Builder setSoundIntensityAlarmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      soundIntensityAlarm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object objectTempAlarm_ = "";
    /**
     * <code>string objectTempAlarm = 2;</code>
     */
    public java.lang.String getObjectTempAlarm() {
      java.lang.Object ref = objectTempAlarm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectTempAlarm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string objectTempAlarm = 2;</code>
     */
    public com.google.protobuf.ByteString
        getObjectTempAlarmBytes() {
      java.lang.Object ref = objectTempAlarm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectTempAlarm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string objectTempAlarm = 2;</code>
     */
    public Builder setObjectTempAlarm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectTempAlarm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string objectTempAlarm = 2;</code>
     */
    public Builder clearObjectTempAlarm() {
      
      objectTempAlarm_ = getDefaultInstance().getObjectTempAlarm();
      onChanged();
      return this;
    }
    /**
     * <code>string objectTempAlarm = 2;</code>
     */
    public Builder setObjectTempAlarmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objectTempAlarm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object airPressureAlarm_ = "";
    /**
     * <code>string airPressureAlarm = 3;</code>
     */
    public java.lang.String getAirPressureAlarm() {
      java.lang.Object ref = airPressureAlarm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        airPressureAlarm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string airPressureAlarm = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAirPressureAlarmBytes() {
      java.lang.Object ref = airPressureAlarm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        airPressureAlarm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string airPressureAlarm = 3;</code>
     */
    public Builder setAirPressureAlarm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      airPressureAlarm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string airPressureAlarm = 3;</code>
     */
    public Builder clearAirPressureAlarm() {
      
      airPressureAlarm_ = getDefaultInstance().getAirPressureAlarm();
      onChanged();
      return this;
    }
    /**
     * <code>string airPressureAlarm = 3;</code>
     */
    public Builder setAirPressureAlarmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      airPressureAlarm_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:invasionAlarm)
  }

  // @@protoc_insertion_point(class_scope:invasionAlarm)
  private static final grpc.invasionEvent.invasionAlarm DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.invasionEvent.invasionAlarm();
  }

  public static grpc.invasionEvent.invasionAlarm getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<invasionAlarm>
      PARSER = new com.google.protobuf.AbstractParser<invasionAlarm>() {
    @java.lang.Override
    public invasionAlarm parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new invasionAlarm(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<invasionAlarm> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<invasionAlarm> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.invasionEvent.invasionAlarm getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

