// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invasionEvent.proto

package grpc.invasionEvent;

public final class InvasionEventImpl {
  private InvasionEventImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_checkRoomStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_checkRoomStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_invasionAlarm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_invasionAlarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023invasionEvent.proto\"b\n\017checkRoomStatus" +
      "\022\026\n\016firstRoomSound\030\001 \001(\002\022\034\n\024firstRoomTem" +
      "perature\030\002 \001(\002\022\031\n\021firstRoomPressure\030\003 \001(" +
      "\002\"_\n\rinvasionAlarm\022\033\n\023soundIntensityAlar" +
      "m\030\001 \001(\t\022\027\n\017objectTempAlarm\030\002 \001(\t\022\030\n\020airP" +
      "ressureAlarm\030\003 \001(\t2E\n\rinvasionEvent\0224\n\nr" +
      "oomStatus\022\020.checkRoomStatus\032\016.invasionAl" +
      "arm\"\000(\0010\001B)\n\022grpc.invasionEventB\021Invasio" +
      "nEventImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_checkRoomStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_checkRoomStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_checkRoomStatus_descriptor,
        new java.lang.String[] { "FirstRoomSound", "FirstRoomTemperature", "FirstRoomPressure", });
    internal_static_invasionAlarm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_invasionAlarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_invasionAlarm_descriptor,
        new java.lang.String[] { "SoundIntensityAlarm", "ObjectTempAlarm", "AirPressureAlarm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
