// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pressure.proto

package grpc.pressure;

public interface checkPressureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkPressure)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float firstPressure = 1;</code>
   */
  float getFirstPressure();
}
