// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pressure.proto

package grpc.pressure;

public final class PressureRoomImpl {
  private PressureRoomImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_checkPressure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_checkPressure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PressureAlarm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PressureAlarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pressure.proto\"&\n\rcheckPressure\022\025\n\rfir" +
      "stPressure\030\001 \001(\002\"&\n\rPressureAlarm\022\025\n\rpre" +
      "ssureAlarm\030\001 \001(\t2<\n\010pressure\0220\n\014RoomPres" +
      "sure\022\016.checkPressure\032\016.PressureAlarm\"\000B#" +
      "\n\rgrpc.pressureB\020PressureRoomImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_checkPressure_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_checkPressure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_checkPressure_descriptor,
        new java.lang.String[] { "FirstPressure", });
    internal_static_PressureAlarm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PressureAlarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PressureAlarm_descriptor,
        new java.lang.String[] { "PressureAlarm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
