// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pressure.proto

package grpc.pressure;

public interface PressureAlarmOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PressureAlarm)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pressureAlarm = 1;</code>
   */
  java.lang.String getPressureAlarm();
  /**
   * <code>string pressureAlarm = 1;</code>
   */
  com.google.protobuf.ByteString
      getPressureAlarmBytes();
}
